name: Terraform Destroy

on:
  workflow_dispatch:

# env:
#   BUCKET: anuj-s3-backend
#   TFSTATE_FILE: anuj_terraform.tfstate
#   aws_region: us-east-1

jobs:
  destroy_bucket:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: 'us-east-1'
    steps:
      - name: CheckOut
        uses: actions/checkout@v2
      - name: set up terraform hashicorp
        uses: hashicorp/setup-terraform@v1

      # - name: configure aws credentials
      # - uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      #     aws-region: ${{env.aws_region}}

      - name: terraform init
        id: init
        run: |
          cd s3module
          terraform init
          
      - name: destroy
        id: destroy
        run: |
          cd s3module
          terraform destroy -auto-approve