name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy_bucket:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: 'us-east-1'
    steps:
      - uses: actions/checkout@v1
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
            version: 0.13.4
      - name: Terraform apply
        run: |
          terraform init
          terraform destroy -auto-approve