name: terraform-workflow
# on push 
on:
  push:
    branches: [ "main" ]

# env:
#   BUCKET: anuj-s3-backend
#   TFSTATE_FILE: anuj_terraform.tfstate
  # aws_region: us-east-1

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: 'us-east-1'

    steps:
      uses: actions/checkout@v2
    - name: Terraform hashicorp setup
      uses: hashicorp/setup-terraform@v1

    # - name: Configure AWS Credentials
    # - uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
    #     aws-region: us-east-1

    - name: terraform init
      run: |
        cd s3module
        terraform init
    - name: terraform plan
      run: |
        cd s3module
        terraform plan
    - name: terraform apply
      run: |
        cd s3module 
        terraform apply -auto-approve